import type {Metadata} from 'next';
import {Noto_Sans} from 'next/font/google';
import './globals.css';


const notoSans = Noto_Sans({
  weight: ['200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-noto-sans',
});


export const metadata: Metadata = {
  title: 'Top App project',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
    <body className={`${notoSans.variable}`}>
    {children}
    </body>
    </html>
  );
}
